name = "Harth Hugo Theme"
license = "MIT"
licenselink = "https://github.com/harthsw/harth-hugo-theme/blob/master/LICENSE.md"
description = "Harth Software theme for Hugo static website generator. Uses Bootstrap, suitable for company/technical/blogging."
homepage = "https://github.com/harthsw/harth-hugo-theme"
tags = ["company", "bootstrap", "blog", "technical"]
features = ["company", "bootstrap", "blog", "technical"]
min_version = 0.15

[author]
  name = "Harvey Thompson"
  homepage = "http://www.610yesnolovely.org/"
